# Generated by Django 4.2.3 on 2023-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_notebook_laptop_alter_laptop_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text_post', models.CharField(max_length=1500)),
                ('author_name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pb', 'published'), ('npb', 'not published'), ('ban', 'banned')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField()),
                ('category', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
